### PR TITLE
Some enhancements

### PR DESCRIPTION
**Pull request by lloc**
I hope you don't mind that I changed your plugin like that but I have a client that would like to use this and needed these changes.

Cheers,
Dennis.

### CODE REVIEW

**Comment by stevish-com** [comment]
Wow, no, I don't mind at all. It's released under GPL for that reason. I
will have to look over the code on the options page (one of the
requirements for my client was simplicity and longevity... how long can we
make it last without needing an update), but if that seems to meet my
client's requirements, I will gladly merge this and update the plugin in
the WordPress repository.

Thanks for sharing your work, I really appreciate it!

-Stephen

**Comment by lloc** [comment]
OK, excellent! Hope to here from you soon...

Cheers!

**Comment by stevish-com** [comment]
Hey, I wasn't able to find any input validation on the options page. If
they use a double quote, for instance, in the redirect url, will that break
the input tag on the options page (where it looks like the option value is
dumped verbatim inbetween double quotes in the input tag)? I know Wordpress
has a lot of validation going on behind the scenes, but just want to make
sure that the input for those options is being validated sufficiently.

-Stephen

**Comment by lloc** [comment]
I will add some validation tomorrow.

**Comment by stevish-com** [comment]
I've just been working on validation. I'l go ahead and merge this as-is, then add a callback to a function that sanitizes with esc_url().

**Pull request merged**
